CREATE TABLE "AdminSettings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "storeName" TEXT NOT NULL DEFAULT 'Shop Proyect',
    "supportEmail" TEXT NOT NULL DEFAULT 'support@shopproyect.com',
    "domain" TEXT NOT NULL DEFAULT 'shopproyect.com',
    "country" TEXT NOT NULL DEFAULT 'España',
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 21,
    "taxLabel" TEXT NOT NULL DEFAULT 'IVA',
    "showTaxes" BOOLEAN NOT NULL DEFAULT true,
    "shippingZone" TEXT NOT NULL DEFAULT 'EU shipping zone',
    "estimatedDelivery" TEXT NOT NULL DEFAULT '2-5 días laborables',
    "trackingAutomatic" BOOLEAN NOT NULL DEFAULT false,
    "emailFromName" TEXT NOT NULL DEFAULT 'Shop Proyect',
    "emailFromAddress" TEXT NOT NULL DEFAULT 'no-reply@shopproyect.com',
    "orderConfirmationEmail" BOOLEAN NOT NULL DEFAULT true,
    "theme" TEXT NOT NULL DEFAULT 'Dark premium',
    "accentColor" TEXT NOT NULL DEFAULT 'Emerald / Indigo',
    "themeEditorPrepared" BOOLEAN NOT NULL DEFAULT false,
    "notifyOrders" BOOLEAN NOT NULL DEFAULT true,
    "notifyStock" BOOLEAN NOT NULL DEFAULT true,
    "notifyRefunds" BOOLEAN NOT NULL DEFAULT true,
    "notifyWeekly" BOOLEAN NOT NULL DEFAULT false,
    "compactTableDensity" BOOLEAN NOT NULL DEFAULT false,
    "keyboardShortcuts" BOOLEAN NOT NULL DEFAULT true,
    "autoRefreshDashboard" BOOLEAN NOT NULL DEFAULT true,
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "webhookEndpoint" TEXT NOT NULL DEFAULT 'https://shopproyect.com/api/webhooks',
    "apiKeysLabel" TEXT NOT NULL DEFAULT 'Secret management pending',
    "refundAutomation" BOOLEAN NOT NULL DEFAULT false,
    "shipmentTracking" BOOLEAN NOT NULL DEFAULT false,
    "invoiceActions" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AdminSettings_pkey" PRIMARY KEY ("id")
);
